
import { Inter } from "next/font/google"
import {
    Provider
  } from '@/app/blog/provider'
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Test",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <Provider>
            <html lang="en">
                <body className={inter.className}>{children}</body>
            </html>
        </Provider>
    );
}
